### ISSUE TITLE
Error writing ec config

### ISSUE THREAD

**Issue by mrvruj** [LucaPatarca/MsiPowerCenter#6]
Hi there! I now have the program compiling and running, but it doesn't seem to be working. When I click on the performance button, for example, I see the following exception. When I click Cooler Boost, nothing happens. And I think the fan curve adjuster (bottom left?) is also not working. Apologies if I am doing something silly... still very new to Linux and not familiar with the ins and outs. 

![Screenshot from 2022-03-09 21-58-12](https://user-images.githubusercontent.com/50000590/157580610-e9491804-df65-4ef0-819a-18ac3ac1b9be.png)

**Comment by LucaPatarca** [comment]
It seems that the "backend" is having problems. This is something you should try:

1- Reboot your computer (I know it sounds stupid but reboot is needed to load a kernel module responsible for writing the EC config).
2- Check if the kernel module is loaded. Run `lsmod | grep ec_sys`, it should print something like this `ec_sys                 16384  0`.
3- Provide me the output of this commands `journalctl -b -u msipowercenter` and `systemctl status msipowercenter`.

Also i would like to know what linux distribution you are using, i never tested my program on anything different than arch linux so this would be interesting.

**Comment by mrvruj** [comment]
1) reboot did not fix the issue
2) yes, it says ec_sys 16384 0
3) both give:

Mar 12 15:30:44 vruj-Prestige-15-A10SC backend[1117]: error: Operation not permitted (os error 1)

on many consecutive lines. How can I launch msipowercenter with root permissions? 

I am using Ubuntu 20.04.

**Comment by mrvruj** [comment]
Hey there, just wanted to let you know I solved the issue. The problem was Secure Boot. Once disabled, it works like a charm!

Thanks for making this lovely app -- now I can finally get rid of my useless Windows partition.

**Comment by LucaPatarca** [comment]
Hi, I'm sorry I was unable to reply in time, I'm about to graduate so you can imagine how busy I am. 
I'm really happy to know that you solved the issue, hope you enjoy my app :)
