### ISSUE TITLE
Remove the application

### ISSUE THREAD

**Issue by Loskoss** [LucaPatarca/MsiPowerCenter#9]
Hello i have 
Device-Msi gf65 10ser
Linux distro - Fedora 37
Cause - probably my ec_sys is not enabled cause i dont have debug version 

 So now you know the details and i just wanna uninstall it , how do i do it ?

**Comment by LucaPatarca** [comment]
Hi, I will add an uninstall.sh script soon (hopefully in the next days).
Meanwhile if you want to do it yourself the steps are:
```
sudo systemctl stop msipowercenter
sudo systemctl disable msipowercenter
```
remove directory:
```
/opt/MsiPowerCenter
```
remove files:
```
/etc/modprobe.d/mpc-ec_sys.conf
/etc/modules-load.d/mpc-ec_sys.conf
/etc/systemd/system/msipowercenter.service
/home/$USER/.local/share/applications/msipowercenter.desktop
```

**Comment by Loskoss** [comment]
Thanks a lot man.
